name: Build and release

on:
  push:
    branches:
      - master
    tags:
      - 'v*'
      - 'cabal-install-*'
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 0 * * *'

jobs:
  release-workflow:
    uses: ./.github/workflows/reusable-release.yml
    with:
      branches: '["${{ github.ref }}"]'

  release:
    name: release
    needs: [ "release-workflow" ]
    runs-on: ubuntu-latest
    if: ${{ startsWith(github.ref, 'refs/tags/') || github.event_name == 'schedule' }}
    steps:
      - name: Get current date
        id: date
        run: echo "NIGHTLY_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: artifacts-*
          merge-multiple: true
          path: ./out

      - name: Install requirements
        run: |
          sudo apt-get update && sudo apt-get install -y tar xz-utils
        shell: bash

      - name: build sdists
        run: |
          cabal sdist -o out all
        shell: bash

      - name: Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            ./out/*

      - name: Release nightly
        if: ${{ github.event_name == 'schedule' }}
        uses: softprops/action-gh-release@v1
        with:
          tag_name: nightly-${{ env.NIGHTLY_DATE }}
          draft: false
          prerelease: true
          files: |
            ./out/*
